accounts/urls.py
from django.urls import path, include
from accounts import views

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.RegistrationUser.as_view(), name='register'),
]

blog/urls.py
from django.urls import path
from blog import views


urlpatterns = [
    path('', views.index, name='home'),
    path('post-list/', views.PostList.as_view(), name='post_list'),
    path('post/<int:pk>/', views.PostDetail.as_view(), name='post_detail'),
    path('post-create/', views.PostCreate.as_view(), name='post_create'),
    path('post-update/<int:pk>/', views.PostUpdate.as_view(), name='post_update'),

    path('comment/<int:pk>/', views.CommentCreate.as_view(), name='comment_create'),

    path('user-posts/', views.UserPostList.as_view(), name='user_posts'),
    path('profile/<int:pk>/', views.ProfilePublic.as_view(), name='profile_public'),
]

practical_work_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('blog.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser


class UserModel(AbstractUser):
    pass

blog/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Post(models.Model):
    STATUS = [
        ('DRA', 'Draft'),
        ('PUB', 'Published'),
    ]

    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    content = models.TextField()
    status = models.CharField(max_length=3, choices=STATUS, default='Draft')
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    comment = models.TextField()
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE)
    is_published = models.BooleanField(default=False)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.comment

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from accounts.models import UserModel
from django import forms


class CastomUserForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = UserModel
        fields = UserCreationForm.Meta.fields + ('email',)

blog/forms.py
from django import forms

from blog.models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'status']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']

accounts/views.py
from django.contrib.auth import login
from django.urls import reverse_lazy
from django.views.generic import FormView
from accounts.forms import CastomUserForm


class RegistrationUser(FormView):
    form_class = CastomUserForm
    template_name = 'registration/register.html'
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return super(RegistrationUser, self).form_valid(form)

blog/views.py
from django.contrib.auth import get_user_model
from django.core.mail import send_mail
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView

from blog.models import Post, Comment
from blog.forms import PostForm, CommentForm

User = get_user_model()


def index(request):
    return render(request, 'blog/index.html', context={})


class CommentCreate(CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'blog/comment_create.html'
    success_url = reverse_lazy('post_list')

    def form_valid(self, form):
        comment = form.cleaned_data['comment']
        post = Post.objects.get(pk=int(self.kwargs['pk']))
        form.instance.post = post
        if self.request.user.is_authenticated:
            form.instance.author = self.request.user
        send_mail('Blog info', f'Check a new comment {comment}',
                  'blog@gmail.com',
                  ['admin@gmail.com'])
        return super(CommentCreate, self).form_valid(form)


class PostList(ListView):
    model = Post
    template_name = 'blog/post_list.html'
    context_object_name = 'posts'
    queryset = Post.objects.select_related('author').prefetch_related('comment_set__author').filter(status='PUB')
    paginate_by = 2


class PostCreate(CreateView):
    model = Post
    form_class = PostForm
    template_name = 'blog/post_create.html'

    def get_success_url(self):
        return reverse_lazy('profile_public', kwargs={'pk': self.request.user.id})

    def form_valid(self, form):
        # self.object = form.save(commit=False)
        form.instance.author = self.request.user
        send_mail('Blog info', 'Check a new comment post', 'blog@gmail.com', ['admin@gmail.com'])
        return super(PostCreate, self).form_valid(form)


class PostUpdate(UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'blog/post_update.html'

    def get_success_url(self):
        return reverse_lazy('profile_public', kwargs={'pk': self.request.user.id})


class PostDetail(DetailView):
    model = Post
    queryset = Post.objects.all()
    pk_url_kwarg = 'pk'
    template_name = 'blog/post_detaile.html'


class UserPostList(ListView):
    model = User
    queryset = User.objects.prefetch_related('post_set')
    template_name = 'blog/user_posts_list.html'
    context_object_name = 'users'


class ProfilePublic(DetailView):
    model = User
    context_object_name = 'user'
    pk_url_kwarg = 'pk'
    template_name = 'blog/profile_public.html'

blog/templates/blog/comment_create.html
{% extends 'base.html' %}

{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'blog/css/index.css' %}">
{% endblock %}

{% block title %}
    Commit
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md">
            <form action="" method="post">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="id_comment" class="form-label">Comment</label>
                    <textarea class="form-control" name="comment" id="id_comment" placeholder="write your comment"
                    rows="5"></textarea>
                </div>
                <button type="submit" class="btn btn-color text-white">Add comment</button>
            </form>
        </div>
    </div>

{#    <h1>Post create</h1>#}
{#    <form action="" method="post">#}
{#        {% csrf_token %}#}
{#        {{ form.as_p }}#}
{#        <button type="submit"> publish</button>#}
{#    </form>#}
{% endblock %}

blog/templates/blog/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    Index
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md">
                <h1 class="display-3">Home page</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-md">
                <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
                    <div class="carousel-indicators">
                        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0"
                                class="active" aria-current="true" aria-label="Slide 1"></button>
                        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"
                                aria-label="Slide 2"></button>
                        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"
                                aria-label="Slide 3"></button>
                    </div>
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img src="{% static 'blog/img/Blog-Comments.jpg' %}" class="d-block w-100 img" alt="...">
                        </div>
                        <div class="carousel-item">
                            <img src="{% static 'blog/img/want48167-1QDZGC1487814769.jpg' %}" class="d-block w-100 img"
                                 alt="...">
                        </div>
                        <div class="carousel-item">
                            <img src="{% static 'blog/img/Maximize-Your-Traffic-and-Branding-with-Blog-Commenting.jpg' %}"
                                 class="d-block w-100 img" alt="...">
                        </div>
                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators"
                            data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Предыдущий</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators"
                            data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Следующий</span>
                    </button>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

blog/templates/blog/post_create.html
{% extends 'base.html' %}

{% block title %}
    Posts
{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_title" class="form-label">Title</label>
            <input id="id_title" type="text" class="form-control" name="title" >

            <label for="id_content" class="form-label">Post</label>
            <textarea class="form-control" id="id_content" cols="30" rows="10" name="content"></textarea>

            <label for="id_status" class="form-label">Status</label>
            <select class="form-select" id="id_status" name="status">
                <option value="DRA" selected>Draft</option>
                <option value="PUB">Pablished</option>
            </select>
        </div>
        <button type="submit" class="btn btn-color">Create</button>
    </form>

{#    <h1>Post create</h1>#}
{#    <form action="" method="post">#}
{#        {% csrf_token %}#}
{#        {{ form.as_p }}#}
{#        <button type="submit"> Create </button>#}
{#    </form>#}
{% endblock %}

blog/templates/blog/post_detaile.html
{% extends 'base.html' %}

{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'blog/css/index.css' %}">
{% endblock %}

{% block title %}
    Posts
{% endblock %}

{% block content %}
    <div>
        {{ post.title }}, Author {{ post.user_set }}
        <p>{{ post.content }}</p>
    </div>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}

{% block title %}
    Posts
{% endblock %}

{% block content %}
    <div class="content">

        {% for post in posts %}
            <div class="card mb-2">
                <h5 class="card-header">{{ post.author }}</h5>
                <div class="card-body">
                    <h5 class="card-title">{{ post.title }}</h5>
                    <p class="card-text">{{ post.content }}</p>
                    <p>
                        <a class="btn btn-color text-white" data-bs-toggle="collapse" href="#Post{{ post.id }}"
                           role="button"
                           aria-expanded="false" aria-controls="collapseExample">
                            Comments
                        </a>
                        <a class="btn btn-color text-white" href="{% url 'comment_create' pk=post.id %}">Add comment</a>
                    </p>
                    <div class="collapse" id="Post{{ post.id }}">

                        {% for comment in post.comment_set.all %}
                            <div class="card mb-2">
                                {% if comment.is_published is True %}
                                    {% if comment.author is None %}
                                        <h5 class="card-header">Anonymous</h5>
                                    {% else %}
                                        <h5 class="card-header">{{ comment.author }}</h5>
                                    {% endif %}
                                    <div class="card-body">
                                        <p class="card-title">{{ comment.comment }}</p>
                                    </div>
                                {% endif %}
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

blog/templates/blog/post_update.html
{% extends 'base.html' %}

{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'blog/css/index.css' %}">
{% endblock %}

{% block title %}
    Posts
{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_title" class="form-label">Title</label>
            <input id="id_title" type="text" class="form-control" name="title" value="{{ post.title }}">

            <label for="id_content" class="form-label">Post</label>
            <textarea class="form-control" id="id_content" cols="30" rows="10"
                      name="content">{{ post.content }}</textarea>

            <label for="id_status" class="form-label">Status</label>
            <select class="form-select" id="id_status" name="status">
                <option value="DRA" selected>Draft</option>
                <option value="PUB">Pablished</option>
            </select>
        </div>
        <button type="submit" class="btn btn-color">Create</button>
    </form>

{% endblock %}

blog/templates/blog/profile_public.html
{% extends 'base.html' %}

{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'blog/css/index.css' %}">
{% endblock %}

{% block title %}
    Profile
{% endblock %}

{% block content %}
    <h1>Profile | <a class="btn btn-color text-white" href="{% url 'post_create' %}"> Create post</a></h1>
    <div class="row mt-5">
        <div class="col-md">
            <h2 class="header">
                Author - {{ user.username }}<br>
                Email - {{ user.email }}
            </h2>
        </div>
    </div>

    <div class="row mt-5">
        <div class="col-md">
            <div class="content">
                {% for post in user.post_set.all %}
                    <div class="card mb-2">
                        <h5 class="card-header">{{ post.author }}</h5>
                        <div class="card-body">
                            <h5 class="card-title">{{ post.title }}</h5>
                            <p class="card-text">{{ post.content }}</p>
                            <p>
                                <a class="btn btn-color text-white" data-bs-toggle="collapse" href="#Post{{ post.id }}"
                                   role="button"
                                   aria-expanded="false" aria-controls="collapseExample">
                                    Comments
                                </a>
                                <a class="btn btn-color text-white" href="{% url 'comment_create' pk=post.id %}">Add
                                    comment</a>
                                <span class="update_btn text-end">
                                <a class="btn btn-color text-white" href="{% url 'post_update' pk=post.id %}">Update
                                    post</a>
                                </span>
                            </p>
                            <div class="collapse" id="Post{{ post.id }}">

                                {% for comment in post.comment_set.all %}
                                    <div class="card mb-2">
                                        {% if comment.is_published is True %}
                                            {% if comment.author is None %}
                                                <h5 class="card-header">Anonymous</h5>
                                            {% else %}
                                                <h5 class="card-header">{{ comment.author }}</h5>
                                            {% endif %}
                                            <div class="card-body">
                                                <p class="card-title">{{ comment.comment }}</p>
                                            </div>
                                        {% endif %}
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                {% endfor %}

            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/user_posts_list.html
{% extends 'base.html' %}

{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'blog/css/index.css' %}">
{% endblock %}

{% block title %}
    User posts
{% endblock %}

{% block content %}
    {% for user in users %}
        User -- {{ user.username }} have
        {{ user.post_set.all.count }} posts<br><br>
    {% endfor %}

    {{ agg.post__count }}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} {% endblock %}</title>
    {#    {% block css %} {% endblock %}#}

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

    {% load static %}
    <link rel="stylesheet" href="{% static 'blog/css/index.css' %}">

</head >
<body class="d-flex flex-column min-vh-100">

<header>
    <div class="container-md">
        <div class="row">
            <div class="col-md-6 text-white">
                <div class="logo">
                    <h3 class="display-3">Blog <small>
                        <mark class="">&</mark>
                        comments</small></h3>
                </div>
            </div>
            <div class="col-md-6 text-end text-white p-4">
                <div class="registration ">
                    {% if user.is_authenticated %}
                        {{ user.username }} /
                        <a href="{% url 'logout' %}" class="text-decoration-none text-white">Logout</a>
                    {% else %}
                        <a href="{% url 'register' %}" class="text-decoration-none text-white">Register</a> /
                        <a href="{% url 'login' %}" class="text-decoration-none text-white">Login</a>
                    {% endif %}
                </div>
            </div>
            <div class="row">
                <div class="col-md text-end text-white">
                    <div class="settings">
                        <div class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                               aria-expanded="false">
                                Settings
                            </a>
                            <ul class="dropdown-menu dropdown-menu-md-end text-end">
                                {% if user.is_authenticated %}
                                    <li><a class="dropdown-item"
                                           href="{% url 'profile_public' pk=user.id %}">Profile</a>
                                    </li>
                                {% endif %}
                                <li><a class="dropdown-item" href="/admin">Adminka</a></li>
                                <li><a class="dropdown-item" href="#">About us</a></li>
                                <li><a class="dropdown-item" href="#">Contack form</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</header>

<section>
    <div class="container overflow-hidden">
        <div class="row gx-3">
            <div class="col-md-2">
                <div class="navigations border-end border-2 border-primary">
                    <h1>Navi bar</h1>
                    <div class="navi_bar">
                        <nav class="nav flex-column">
                            <a class="nav-link active link-color" aria-current="page" href="{% url 'home' %}">Home</a>
                            <a class="nav-link link-color" href="{% url 'post_list' %}">Post list</a>
                            <a class="nav-link link-color" href="{% url 'user_posts' %}">User posts</a>
                        </nav>
                    </div>
                </div>
            </div>
            <div class="col-md-10">
                <div class="content">
                    {% block content %} {% endblock %}
                </div>
            </div>
        </div>
        <div class="row-md">
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                        </li>
                    {% endif %}
                    {% for p in paginator.page_range %}
                        {% if p == page_obj.number %}
                            <li class="page-item active"><a class="page-link" href="?page={{ p }}">{{ p }}</a></li>
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ p }}">{{ p }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
</section>


<footer class="p-3 mt-auto">
    footer
</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
        crossorigin="anonymous"></script>
</body>
</html>